# Generated by Django 5.0 on 2024-05-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtask', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('Duetime', models.DateTimeField()),
                ('userName', models.CharField(max_length=60)),
            ],
        ),
    ]
